plugins:
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/mocha"
  - "@dotcom-tool-kit/eslint"
  - "@dotcom-tool-kit/lint-staged-npm"
  - "./toolkit/karma"
hooks:
  test:local:
    - Eslint
    - Mocha
    - Karma
  test:ci:
    - Eslint
    - Mocha
options:
  "@dotcom-tool-kit/circleci":
    nodeVersion:
      - '18.16'
      - '16.20'
  "@dotcom-tool-kit/mocha":
    files: test/node/**/*.js
    configPath: ".mocharc.json"
